// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geeamltdvtlxbujwzekm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlZWFtbHRkdnRseGJ1and6ZWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDExMzksImV4cCI6MjA2NDE3NzEzOX0.lvmG2FHeX9mC4_X2cSw7Ku_Be3vIjasGYLt8Xjdqhvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);